"""Tutelary 契约内核。

词汇表（types）、事件与总线（events）、五端口（ports）、生命周期（lifecycle）
与装配器（assembler）。只提供语法，不做 IO、不做调度、零第三方依赖——
约束见 docs/03-kernel.md §0。组件按子模块 import（``from
tutelary.core.types import ...``）；本命名空间的重导出仅为使用便利。
"""

from tutelary.core.assembler import Assembler, Tutelary
from tutelary.core.errors import (
    BusContractError,
    CircularRequirementError,
    ConfigValidationError,
    DuplicatePortError,
    MissingPortError,
    TutelaryError,
)
from tutelary.core.events import (
    BudgetBreached,
    Bus,
    CompactNotification,
    CompactStarted,
    ErrorEvent,
    Event,
    HookEvent,
    LLMEvent,
    LoopComplete,
    PermissionRequest,
    PermissionResponse,
    RetryEvent,
    StreamText,
    ThinkingText,
    ToolResultEvent,
    ToolUseEvent,
    TurnCommitted,
    TurnComplete,
    TurnStarted,
    UsageEvent,
)
from tutelary.core.fakes import FakeBus, FakeExecutor, FakeMemory, FakeProvider, FakeSandbox
from tutelary.core.lifecycle import Component, Disposable, EffectStack, PortSpec
from tutelary.core.ports import Executor, Memory, Policy, Provider, Sandbox, Tool
from tutelary.core.types import (
    Allow,
    ContentBlock,
    Decision,
    Deny,
    ExecResult,
    ExecSpec,
    LLMRequest,
    MemoryHit,
    MemoryScope,
    Message,
    Suspend,
    TextBlock,
    ThinkingBlock,
    ToolCall,
    ToolResult,
    ToolResultBlock,
    ToolSpec,
    ToolUseBlock,
    Usage,
)

__all__ = [
    "Allow",
    "Assembler",
    "BudgetBreached",
    "Bus",
    "BusContractError",
    "CircularRequirementError",
    "CompactNotification",
    "CompactStarted",
    "Component",
    "ConfigValidationError",
    "ContentBlock",
    "Decision",
    "Deny",
    "Disposable",
    "DuplicatePortError",
    "EffectStack",
    "ErrorEvent",
    "Event",
    "ExecResult",
    "ExecSpec",
    "Executor",
    "FakeBus",
    "FakeExecutor",
    "FakeMemory",
    "FakeProvider",
    "FakeSandbox",
    "HookEvent",
    "LLMEvent",
    "LLMRequest",
    "LoopComplete",
    "Memory",
    "MemoryHit",
    "MemoryScope",
    "Message",
    "MissingPortError",
    "PermissionRequest",
    "PermissionResponse",
    "Policy",
    "PortSpec",
    "Provider",
    "RetryEvent",
    "Sandbox",
    "StreamText",
    "Suspend",
    "TextBlock",
    "ThinkingBlock",
    "ThinkingText",
    "Tool",
    "ToolCall",
    "ToolResult",
    "ToolResultBlock",
    "ToolResultEvent",
    "ToolSpec",
    "ToolUseBlock",
    "ToolUseEvent",
    "TurnCommitted",
    "TurnComplete",
    "TurnStarted",
    "Tutelary",
    "TutelaryError",
    "Usage",
    "UsageEvent",
]
